# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/Polygon.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Point32_pb2 as ros_dot_geometry__msgs_dot_Point32__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fros/geometry_msgs/Polygon.proto\x12\x11ros.geometry_msgs\x1a\x1fros/geometry_msgs/Point32.proto\"5\n\x07Polygon\x12*\n\x06points\x18\x01 \x03(\x0b\x32\x1a.ros.geometry_msgs.Point32b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ros.geometry_msgs.Polygon_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POLYGON._serialized_start=87
  _POLYGON._serialized_end=140
# @@protoc_insertion_point(module_scope)
