# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/geometry_msgs/TwistWithCovarianceStamped.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import TwistWithCovariance_pb2 as ros_dot_geometry__msgs_dot_TwistWithCovariance__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n2ros/geometry_msgs/TwistWithCovarianceStamped.proto\x12\x11ros.geometry_msgs\x1a+ros/geometry_msgs/TwistWithCovariance.proto\x1a\x19ros/std_msgs/Header.proto\"y\n\x1aTwistWithCovarianceStamped\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x35\n\x05twist\x18\x02 \x01(\x0b\x32&.ros.geometry_msgs.TwistWithCovarianceb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ros.geometry_msgs.TwistWithCovarianceStamped_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TWISTWITHCOVARIANCESTAMPED._serialized_start=145
  _TWISTWITHCOVARIANCESTAMPED._serialized_end=266
# @@protoc_insertion_point(module_scope)
