# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/ackermann_msgs/AckermannDriveStamped.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.ackermann_msgs import AckermannDrive_pb2 as ros_dot_ackermann__msgs_dot_AckermannDrive__pb2
from ros.std_msgs import Header_pb2 as ros_dot_std__msgs_dot_Header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.ros/ackermann_msgs/AckermannDriveStamped.proto\x12\x12ros.ackermann_msgs\x1a\'ros/ackermann_msgs/AckermannDrive.proto\x1a\x19ros/std_msgs/Header.proto\"p\n\x15\x41\x63kermannDriveStamped\x12$\n\x06header\x18\x01 \x01(\x0b\x32\x14.ros.std_msgs.Header\x12\x31\n\x05\x64rive\x18\x02 \x01(\x0b\x32\".ros.ackermann_msgs.AckermannDriveb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ros.ackermann_msgs.AckermannDriveStamped_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ACKERMANNDRIVESTAMPED._serialized_start=138
  _ACKERMANNDRIVESTAMPED._serialized_end=250
# @@protoc_insertion_point(module_scope)
