# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/visualization_msgs/MarkerArray.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.visualization_msgs import Marker_pb2 as ros_dot_visualization__msgs_dot_Marker__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(ros/visualization_msgs/MarkerArray.proto\x12\x16ros.visualization_msgs\x1a#ros/visualization_msgs/Marker.proto\">\n\x0bMarkerArray\x12/\n\x07markers\x18\x01 \x03(\x0b\x32\x1e.ros.visualization_msgs.Markerb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ros.visualization_msgs.MarkerArray_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MARKERARRAY._serialized_start=105
  _MARKERARRAY._serialized_end=167
# @@protoc_insertion_point(module_scope)
