# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/shape_msgs/Mesh.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.geometry_msgs import Point_pb2 as ros_dot_geometry__msgs_dot_Point__pb2
from ros.shape_msgs import MeshTriangle_pb2 as ros_dot_shape__msgs_dot_MeshTriangle__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19ros/shape_msgs/Mesh.proto\x12\x0eros.shape_msgs\x1a\x1dros/geometry_msgs/Point.proto\x1a!ros/shape_msgs/MeshTriangle.proto\"c\n\x04Mesh\x12/\n\ttriangles\x18\x01 \x03(\x0b\x32\x1c.ros.shape_msgs.MeshTriangle\x12*\n\x08vertices\x18\x02 \x03(\x0b\x32\x18.ros.geometry_msgs.Pointb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ros.shape_msgs.Mesh_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESH._serialized_start=111
  _MESH._serialized_end=210
# @@protoc_insertion_point(module_scope)
