# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ros/sensor_msgs/JoyFeedbackArray.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ros.sensor_msgs import JoyFeedback_pb2 as ros_dot_sensor__msgs_dot_JoyFeedback__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n&ros/sensor_msgs/JoyFeedbackArray.proto\x12\x0fros.sensor_msgs\x1a!ros/sensor_msgs/JoyFeedback.proto\"?\n\x10JoyFeedbackArray\x12+\n\x05\x61rray\x18\x01 \x03(\x0b\x32\x1c.ros.sensor_msgs.JoyFeedbackb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ros.sensor_msgs.JoyFeedbackArray_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _JOYFEEDBACKARRAY._serialized_start=94
  _JOYFEEDBACKARRAY._serialized_end=157
# @@protoc_insertion_point(module_scope)
